### ISSUE TITLE
fails on Landsat catalog

### ISSUE THREAD

**Issue by brentfraser** [Terradue/DotNetStac#3]
When using the landsat catalog (https://landsat-stac.s3.amazonaws.com/catalog.json) DotNetStac 0.5.7 fails (tried in Jupyter Notebook).  Granted the STAC version of the catalog is 0.6 so maybe it's too old.

**Comment by emmanuelmathot** [comment]
Hello. Indeed, the library has not been extensively tested on version prior to 1.0.0-beta1. Nevertheless, it should support previous version. I will have a check with that landsat catalog.

**Comment by emmanuelmathot** [comment]
It works using `StacFactory` to load the catalog at first. You can use the `UpgradeToCurrentVersion()` method on all IStacObject interface to upgrade the object to the latest version.

```csharp
IStacCatalog cat06 = await StacFactory.LoadUriAsync(GetUri("Version/landsat06")) as IStacCatalog;
StacCatalog cat = cat06.UpgradeToCurrentVersion();
var children = cat.GetChildren();
IStacCatalog subcat06 = children.FirstOrDefault().Value;
StacCatalog subcat = subcat06.UpgradeToCurrentVersion();
```

I anyway discovered a small issue with sub collections. This is fixed in version 0.5.8

**Comment by brentfraser** [comment]
Nice!  Thanks!

**Comment by brentfraser** [comment]
Perhaps a runtime configuration setting in DotNetStac would be a better solution than requiring a "UpgradeToCurrentVersion" before calling a parse method?

**Comment by brentfraser** [comment]
Using the notebook as a guide example, I do:

```
        public static void ListChildrensItemsAndAssets(IStacCatalog catalog, string prefix = "", int limit = 2)
        {
            // Get children first (sub catalogs and collections)
            foreach (var child_any_version in catalog.GetChildren().Values.Take(limit) )
            {
                IStacCatalog child = child_any_version.UpgradeToCurrentVersion();
                Console.Out.WriteLine(prefix + child.Id + ": " + child.Description);

                foreach (var item_any_version in child.GetItems().Values.Take(limit))
                {
                    IStacItem item = item_any_version.UpgradeToCurrentVersion();
                    Console.Out.WriteLine(prefix + " " + item.Id);
                    foreach (var asset in item.Assets.Values)
                    {
                        Console.Out.WriteLine(prefix + " *[" + asset.MediaType + "] " + asset.Uri);
                    }
                }

                ListChildrensItemsAndAssets(child, prefix + " ");
            }
        }

```

Note the` IStacItem item = item_any_version.UpgradeToCurrentVersion();`.  The landsat catalog generates:

```
System.IO.InvalidDataException
  HResult=0x80131501
  Message=The document is not a STAC document. No 'stac_version' property found
  Source=DotNetStac
  StackTrace:
   at Stac.Item.StacItem.LoadStacItem(JToken jsonRoot) in src\DotNetStac\Item\StacItem.Helper.cs:line 43
   at Stac.Item.StacItem.LoadJToken(JToken jsonRoot, Uri uri) in src\DotNetStac\Item\StacItem.Helper.cs:line 33
   at Stac.StacFactory.<>c__DisplayClass0_0.<LoadUriAsync>b__0(Task`1 json) in src\DotNetStac\StacFactory.cs:line 21
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

```

An Item should not require a stac_version?

**Comment by emmanuelmathot** [comment]
right, in v0.6.0 `stac_version` field was not part of the spec (https://github.com/radiantearth/stac-spec/blob/v0.6.0/item-spec/item-spec.md). Will correct that in the next version
